title: Gestión Ágil - SocioUnido
description: Registro semanal de las ceremonias de Scrum y hoja de ruta del proyecto "SocioUnido"
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"
baseurl: "/scrum"
