title: Gestión ágil & Hoja de ruta
description: Registro semanal de las ceremonias de Scrum y hoja de ruta definida de "SocioUnido"
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"
baseurl: "/scrum"
